<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Webpatser\Uuid\Uuid;

class Brand extends Model
{
    //

    static function getBrands(){

    	return $brands = 
    	[
    		'Masterflo',
			'Crosby',
			'Tyco',
			'Emerson',
			'Pentair',
			'Dresser',
			'Cameron',
			'Wier',
			'Flowserve',
			'Sanyo',
			'Fujitsu',
			'Swagelok',
			'Parker',
			'Norgren',
			'Asco',
			'Festo',
			'Liebherr',
			'Atlas',
			'Rexroth',
			'Hagglunds',
			'Mobil',
			'Bosch',
			'Messer',
			'Kemppi',
			'Hypertherm',
			'Lifmex',
			'Prestar',
			'Toho',
			'Wallclimb',
			'Safemax',
			'SKF',
			'ORB',
			'Benke',
			'Feam',
			'Varnost',
			'Technor',
			'Nuova ASP',
			'Pixavi',
			'Vodec',
			'Syscom',
			'Bacab',
			'Krohne',
			'Total',
			'Honeywell',
			'FMC Technologies',
			'Canalta',
			'Fluenta',
			'Belman',
			'Superlok',
			'Baumer',
			'Meriam',
			'Valvtechnologies',
			'Toyo',
			'Teksan',
			'KwangShin',
			'Komoto',
			'IRD Balancing',
			'SAI',
			'Lovejoy',
			'Cresent',
			'FDC',
			'Redrock',
			'Koike',
			'Victory',
			'Gullco',
			'SMC',
			'Loadwise',
			'3D Valve',
			'ABB',
			'Aggreko',
			'AWC',
			'AIT',
			'Alco',
			'Angus Fire',
			'Arbor',
			'AO Smith',
			'Golden harbor',
			'ARI Armaturen',
			'Ascent EMIRATES',
			'Atlas Copco',
			'Avant',
			'Bonney Forge',
			'BDS Machinen',
			'Bechem',
			'Belden',
			'Borouge',
			'Bristol',
			'Bureau Veritas',
			'Cat',
			'Catlow',
			'Cim Tek',
			'Elster',
			'Chalwyn',
			'Chemisafe',
			'CMC',
			'Cofra',
			'Combilift',
			'Crane',
			'Douglas Chero',
			'Diamond Walraven',
			'Dixon',
			'Dunlop Hiflex',
			'Cella',
			'Euromisure',
			'Erse',
			'EST',
			'Eyevex',
			'ExxonMobil',
			'Esso',
			'FG Wilson',
			'FirePro',
			'Flygt',
			'Foxtam',
			'Bolle',
			'Elmar NOV',
			'Frigidaire',
			'GWC',
			'Gweld',
			'Hochiki',
			'KoneCraines',
			'Kumkang',
			'Lafon Technologies',
			'Luchs',
			'Meclube',
			'Moldex',
			'Mosa',
			'Motorola Hytera',
			'Naffco',
			'Nibco',
			'Oerlikon Metco',
			'Omax ',
			'Philips',
			'Phoenix',
			'Polyco',
			'Roda Deaco',
			'Reliable',
			'Pyropress',
			'Prysmian',
			'Schoeller',
			'Schrack Technik',
			'Scope',
			'Seetru',
			'Sick',
			'Siemens',
			'Speakman',
			'Tercel',
			'Thwaites',
			'Torishima',
			'Trafag',
			'Vimec Valves',
			'Weir',
			'Whirlpool',
			'Wika',
			'Wilden',
			'Viking',
			'FTI',
			'Pulsafeeder',
			'Travaini',
			'Nov Mono',
			'Rovatti',
			'Zenit',
			'Stanflo',
			'Groz',
			'Quincy',
			'Valiadis',
			'Euromotori',
			'Imak',
			'Almatec',
			'Wilo',
			'Alphagomma',
			'Mikalor',
			'Sunnyhose',
			'Pisco',
			'RK Kutting',
			'ZEC',
			'Enerpac',
			'Arco',
			'Red Wing Shoes',
			'Venus',
			'Pyramex',
			'FSI',
			'Ergodyne',
			'Haimo',
			'Hoerbiger',
			'Bauer',
			'Hyundai',
			'Palazzoli',
			'Daeyang',
			'Ducab',
			'Nexans',
			'Victor',
			'Ramcro',
			'Bartec',
			'3M',
			'Burndy',
			'Kopex',
			'Burn',
			'Larsen & Toubro',
			'Edison',
			'Fluke',
			'Schneider',
			'Critchley',
			'Megger',
			'Efen',
			'Epcos',
			'Midpoint',
			'Galperti',
			'Flexim',
			'MTU',
			'Detroit Diesel',
			'Abro',
			'Endura',
			'Hitachi',
			'Daikin',
			'Rollstud',
			'Mrodrigues',
			'Chemetall',
			'Powermaster',
			'FinnSonic',
			'ELGI',
			'AAW',
			'KE Kelit',
			'Vallourec',
			'FireTrace',
			'Autronica',
			'Hygood',
			'Ansul',
			'CooperSafety',
			'ACAF',
			'Signaline',
			'Checkmate Fire',
			'Crowcon',
			'FireDos',
			'DPPUL',
			'Morley IAS',
			'Protectowire',
			'Context Plus',
			'Himoinsa',
			'Perkins',
			'Cummins',
			'Stamford',
			'Murphy',
			'Lister Petter',
			'Optima',
			'LUXE',
			'Interfit',
			'ULMA',
			'AMPO',
			'ERNE',
			'Le bronze industriel',
			'USC United steel',
			'Al Mufaddal',
			'Golden Harbour',
			'Nam Kwang',
			'Donghwa entec ',
			'EPP',
			'INOR',
			'TROLINER',
			'PIPE ROBOTECH',
			'SAERTEX',
			'PRIMUS',
			'IMPREG',
			'BRANDANBURGER',
			'IST',
			'IBG',
			'RST',
			'IBAK',
			'Flowchem Industries',
			'Gems Sensore',
			'Simer',
			'ControlAirInk',
			'NIVELCO',
			'Kleeve',
			'FUJI Electrics',
			'SMAR',
			'DWYER',
			'BSSTech',
			'Orient Lines Elevators',
			'Makita',
			'Mitsubishi',
			'John Deere',
			'Aksa',
			'Doosan',
			'Stanley',
			'SAIT',
			'Jotun',
			'Boral',
			'Sterling',
			'Ayhace',
			'Al Namariq',
			'Gyproc',
			'Fixman',
			'NicholsonNational Paints',
			'Robin subaru',
			'Abra',
			'Presto',
			'loctite',
			'weicon interflex',
			'Bondo',
			'hoiki',
			'prestar',
			'fisco',
			'Yale',
			'Tyrolit',
			'Filex',
			'Esab',
			'Dewalt',
			'EVERLAS',
			'DURA',
			'HQ',
			'LEOPAD',
			'BSI',
			'SAF Panels',
			'C-MET',
			'Dolphin',
			'Riken Keiki GmbH',
			'IYYM',
			'Toshniwal',
			'Biogreen',
			'Genebre',
			'TecniKabel',
			'Orion Instruments',
			'Finetek',
			'Valsteam',
			'RAKHOH',
			'Ultrafilter',
			'Ayvaz',
			'TNF',
			'Incertech',
			'Bitherm group',
			'Schwer fittings',
			'Camtech',
			'Rockwheel',
			'Pramac',
			'Silla',
			'HC',
			'Stetter',
			'APCE',
			'Turbosol',
			'Terex',
			'Conquip and Komptech',
			'Chicago Pneumatic',
			'LMC Makina Sanayi',
			'Schwing',
			'doe',
			'APG Arch',
			'Microsoft',
			'MARTYR ANODES',
			'Wacker-Neuson',
			'TITAN',
			'HYTORC',
			'Great Steel & Metals',
			'AOTAI',
			'protecta',
			'Microgard',
			'Pezzol',
			'Portwest',
			'iSoil Impianti',
			'Liberty',
			'Lee Cooper',
			'lalizas',
			'Lakeland',
			'Cantrel',
			'Justrite',
			'Heartsine',
			'Garret',
			'Giasco',
			'Encon',
			'DBI SALA',
			'Cirrus',
			'Safety Plus',
			'Red Cap',
			'Bicap',
			'Timberland pro',
			'Scottsafety',
			'Salisburry',
			'Uvex',
			'Streamlight',
			'Trellchem',
			'VF Imagewear',
			'Workmaster',
			'EthosEnergy',
			'Ansell',
			'Castolin Eutectic',
			'LONTRIN',
			'DUYAR',
			'TROX',
			'ROBINAR',
			'SUNDCO',
			'SAGLNOMIYA',
			'INTERDRYORS',
			'MAKSAL',
			'HERMATIC COMPRESSORS',
			'CASTEL',
			'DANFOSS',
			'GALCO',
			'MATSUSHITA',
			'IMPERIAL',
			'BITZER',
			'DURO DYNE',
			'ZENITH',
			'PAL',
			'ARMACELL',
			'SINRO',
			'SPIROVENT',
			'POLYPIPE',
			'PB DUCTAL',
			'AFS',
			'UNTES',
			'FOSTER',
			'KIMMCO',
			'MUELLER',
			'GALA',
			'ABRD',
			'WEISS',
			'UL',
			'FISCHER',
			'ECONOSTO',
			'KingIndia',
			'DuctFix',
			'Heatshield',
			'MACS',
			'IIS',
			'Tecnalco',
			'RWD',
			'jQuerv',
			'knockout',
			'FFES',
			'CIMS',
			'Automaten Technik Baumann',
			'MCS',
			'Car parking technologies',
			'Kemp Technologies',
			'Enforce-IT',
			'WH',
			'Hoeft & Wessel',
			'Kamstrup',
			'Purified air',
			'Powered Aire',
			'Pelco',
			'Rheem',
			'BIT',
			'Asco Kohlensaure AG',
			'Perma-Pipe',
			'Mirine',
			'mybarid',
			'Avdel',
			'Gesipa',
			'BondLoc',
			'Dimension Tools & fasteners',
			'PEM',
			'Ambersil',
			'Power Adhesives',
			'SABIT',
			'Mondeo',
			'Beardow Adams',
			'Hylomar',
			'Araldite',
			'Titgemeyer',
			'Paniker',
			'ACC Silicones',
			'Businessman Luiz Fernando',
			'Nave Cultural',
			'Rubinetterie Brescianem Fourgroup',
			'Tristar',
			'Excel Shattaf',
			'Aquasmart',
			'Uniflo',
			'Electra',
			'Star',
			'Rheem',
			'GRYM',
			'HRYCIUK',
			'vault',
			'NSF',
			'Rochester Midland Corporation',
			'Pioneer Tanks',
			'Jacir-Gohl',
			'Watts Water treatment',
			'Metalaire',
			'Bioclimatic CosaTron',
			'IME',
			'Merten',
			'Sempa',
			'Dynamix',
			'Pennbarry',
			'Redd-i',
			'Jay R Smith',
			'Annicom',
			'Cantech',
			'Wolter',
			'Lau',
			'Winters',
			'Jdff Ductile Fittings',
			'Unifliar',
			'HP',
			'Cisco',
			'West Penn',
			'Stuart Turner',
			'Moffitt Corporation',
			'Leoni',
			'Energy International Corporation',
			'Cleanetics',
			'UVGI Systems',
			'Energy Industrial',
			'Johnson Controls',
			'Dynamix Hydro Systems',
			'Future Technology',
			'BLE',
			'Exiva',
			'Pedrollo',
			'Flexiva',
			'Dotx',
			'Solico',
			'Pegler',
			'MESSER',
			'Hepworth',
			'Alfa Laval',
			'Grundros',
			'Eraslan',
			'Austria Email',
			'Armstrong',
			'Coral',
			'DWD',
			'GENIE',
			'Systemair',
			'Camfil',
			'Cuoghi',
			'CHERNE',
			'PlanGrid',
			'B.E.G.',
			'Soler & palau',
			'Purafil',
			'Lightnin',
			'Victoria Fans',
			'Samyang',
			'Himpel',
			'Winters',
			'P3 ',
			'GPL',
			'Indo-Dan Lampshades',
			'Astral',
			'Fanzic',
			'Comparato Nello',
			'Ninhua',
			'Disan',
			'Ess Ess',
			'Teddington',
			'LightProgress',
			'FlexAir',
			'ClimaEuro',
			'SAFID',
			'ThermAir',
			'Cometal',
			'Biral',
			'The Blue Duct',
			'Samsung',
			'S+S Regeltechnik',
			'Paige',
			'HC Groep',
			'Landis+Gyr',
			'Cera',
			'Prayag',
			'WaterTec',
			'Supreme',
			'Roca',
			'Kohler',
			'Ajay Industrial Corporation',
			'SPIRALITE',
			'Leviton',
			'IAC',
			'LPCB',
			'SMACNA',
			'Ferrodisa',
			'Ferroli',
			'ARISTON',
			'Copeland',
			'Gas',
			'Fan',
			'Dupont',
			'Ecutherm',
			'Eluma',
			'JH',
			'IZOCAM',
			'Kulthorn',
			'HARRIS BRASTAK',
			'IBP',
			'FUCHS',
			'DENA',
			'LG',
			'Toshiba',
			'FSTB',
			'Frigocraft',
			'Flexoflex',
			'Arkema',
			'Bayer',
			'Embraco',
			'Elitech',
			'Skyline',
			'Argos',
			'Hanwa',
			'AromaSense',
			'Exactal',
			'CostX',
			'Trelleborg',
			'Digi',
			'Moonlight',
			'Minny',
			'Pumppro',
			'Suryadeep',
			'BSA',
			'Gelco',
			'Violtee',
			'Doby',
			'Wavin',
			'Homa',
			'Blastrac',
			'Enolgas',
			'Wurth',
			'Armaturen',
			'SergeFerrari',
			'Rubi',
			'Aniplast',
			'Suprema',
			'Oxigeno',
			'Atmosfera',
			'TML',
			'REFLEX',
			'ESPA',
			'DAVEY',
			'FLYGT',
			'WILO',
			'GRUNDFOS',
			'LOWARA',
			'EBARA',
			'Pentair',
			'HALCOR',
			'Silicone RTV',
			'Tembo',
			'Strong Drain',
			'Etalia',
			'Repi',
			'Krypton',
			'Vulcan',
			'Strong weld',
			'Atlantic',
			'Caddy',
			'Erico',
			'Projahn',
			'UIS',
			'Sadaf Gypsum',
			'SFA',
			'Classic',
			'Pennine',
			'Hanwha',
			'E-Param',
			'Cutop',
			'Indon Steel',
			'Lenton',
			'MECHANICS',
			'LARIUS',
			'WINNERFLEX',
			'KRESS',
			'Asmaco',
			'SENCO',
			'BASF',
			'N3',
			'G2100',
			'Attack',
			'Eriflex',
			'CNP',
			'Denso',
			'FLEX',
			'SIT',
			'Neotex',
			'De neef',
			'Fomo Products',
			'Gama',
			'Wacker',
			'UNID',
			'Spolchemie',
			'Piccadilly',
			'Tahweel',
			'TERAZID',
			'ARaymond',
			'SYR',
			'Reddiplex',
			'Pyro Plex',
			'falcon',
			'Alpha',
			'Comensal',
			'HYDROTEC',
			'AWON',
			'ATEN',
			'GMS',
			'Niccons',
			'SITCO',
			'Meineng',
			'CAG CELIK',
			'Energy Star',
			'Avongard',
			'DSI Arteon',
			'Madar',
			'Al Fozan Group',
			'Astral',
			'Huahong',
			'FuhaiMetal',
			'RIPE NCC',
			'AFNIC',
			'WebDev',
			'NetApp',
			'Dell',
			'Kirloskar',
			'PELOX BioChemie',
			'SUPERLUX',
			'STABILA Messgerate',
			'Koster & Co.',
			'Sheffield Insulation',
			'SCHAFER & PETERS',
			'METALFAR',
			'CAMEL',
			'KOBE',
			'Hilbig GmbH',
			'GE Lighting',
			'KDK',
			'Labore',
			'Minim',
			'Navigator',
			'Tempor Incididunt',
			'Keller',
			'Toku',
			'Ambience LED lights & Fixtures',
			'Osram',
			'Venture Lighting',
			'Tridonic',
			'OCC',
			'IML',
			'Kobelco',
			'Power Breezer',
			'CMS',
			'Woerner',
			'Puratek',
			'Expo Technologies',
			'Industronic',
			'PCT Group',
			'Pipe hangers & supports',
			'Vega',
			'Sponge-jet',
			'TI',
			'Tekno',
			'FUMASI',
			'NITTAN',
			'FESCO',
			'JEWEL',
			'JINDAL',
			'FIREFLEX',
			'Island Glass',
			'Rockwell Automation',
			'Ridgid',
			'Kiswel',
			'Most',
			'Legrand',
			'AD Vigano',
			'Fanuc',
			'Red Lion',
			'Eaton',
			'Hoffman',
			'Black & Decker',
			'Zein',
			'Asteco',
			'NSK',
			'Switchgear R&D',
			'USHA',
			'Al Salla',
			'Hepworth',
			'Al Waseef',
			'Technia',
			'ADOS Klinger',
			'National Paints',
			'Optibelt',
			'TTO',
			'IKO',
			'KOYO Torrington',
			'FAG',
			'TIMKEN',
			'RHP',
			'MBG',
			'GreyStone',
			'NAFFCO',
			'TraceTek',
			'BacNet',
			'Carl Stahl',
			'Jaquar',
			'Accutech',
			'Maximator',
			'Alco-valves',
			'Boskalis',
			'Pioneer pumps',
			'Mody pumps',
			'Hughes pumps',
			'PROTALK',
			'NEXEDGE',
			'LUFKIN',
			'Sicame',
			'OTECO',
			'CENTRAVIS. Ruelco',
			'Linde',
			'FENNER',
			'DEXION',
			'bott',
			'Tool Flo',
			'Freddy',
			'BDS',
			'GEOSENSE',
			'DATA TAKER',
			'BRIMOS',
			'GPS',
			'Apollo Valves',
			'WIKA',
			'TERMOPLUS',
			'FOWLER',
			'KERN',
			'TOOLRUNNER',
			'flikart',
			'DICKIES',
			'PELICAN',
			'DRAGER',
			'KUBCO',
			'BOSCH',
			'SKF',
			'KARAM',
			'Fabory',
			'Unbrako',
			'ISAN',
			'RODA DEACO',
			'ALLENCOOPER',
			'ADDISON',
			'SAMURAI',
			'KING TONY',
			'FORCE',
			'W B Alloys.',
			'Prolift',
			'Victory International',
			'King Hoists',
			'HPX',
			'RAZOR',
			'TOHO.',
			'WALLCLIMB',
			'SAFEMAX',
			'POLYCO',
			'COSALT',
			'SALA',
			'Bolle',
			'Bosch.',
			'Eveready',
			'Amaron',
			'Cameron',
			'Technip',
			'Emco',
			'Geveke',
			'acc',
			'Wiha',
			'VIRAX',
			'GOJO',
			'VISHAY.',
			'SIEMENS',
			'Crosly',
			'Wika S-Lok',
			'Ludecke',
			'Alloy.',
			'Balco',
			'Nomex.',
			'Protal',
			'STOUT',
			'Prosafe',
			'TOUGH.',
			'RORIG',
			'STOPAC',
			'TASCO',
			'BISON',
			'WhitMore',
			'Jetlube',
			'Oscar.',
			'ANGEL',
			'ANANT',
			'Schmetz',
			'Ikas',
			'Orion',
			'Nikkiso',
			'Lewa Pumps',
			'Lenco',
			'NG',
			'SNG',
			'LPG',
			'Aesseal.',
			'Fluidtech',
			'Koweld',
			'Silcotub.',
			'Europe Muller',
			'BENKAN',
			'KOFCO',
			'BKL',
			'TPCO',
			'BASTIL',
			'Danhside',
			'BOLEIR',
			'DIG',
			'LINZ.',
			'Hi-Force',
			'Sandvik',
			'Autoclave',
			'Koreel',
			'Devcon',
			'Pressol',
			'Lincoln',
			'Vahn-tech',
			'Tomoe',
			'Gulf valve',
			'Appolo valves',
			'Trip Coils ',
			'Accles & Shelvoke',
			'Elfab',
			'Schaffner',
			'Camille Bauer',
			'Foresta filters',
			'Greenoil',
			'MTR ',
			'Gea',
			'Tecnicomar',
			'Hiliard',
			'Bollfilter',
			'Oren',
			'Hydropro',
			'Bevel',
			'Torquelite',
			'Esco tool',
			'Chris-Marine',
			'Elliott',
			'Climax',
			'HELO',
			'STAHL',
			'KARAM',
			'SWENN',
			'NOVA ROTORS.',
			'PIUSI',
			'GYS',
			'ZENIT',
			'SPARKY',
			'RHODIUS',
			'ABAC',
			'RUELCO',
			'LARGA',
			'HEYCO',
			'GOOD YEAR',
			'GEMELS',
			'FKB',
			'FASTER',
			'EFLEX',
			'DICSA',
			'CONTARINI',
			'KOCSIS',
			'JCB',
			'Gates',
			'Eucaro',
			'Collari per fissaggio tubazioni',
			'Hoke',
			'JESCO',
			'Ostrava',
			'ACM',
			'Rivit',
			'Outokumpu',
			'Sosta',
			'Industriali',
			'Metalfar Prodotti',
			'Ulma Forja',
			'Officine Ambrogio Melesi',
			'Felix Technology',
			'VIRAJ',
			'Douglas Chero',
			'Kumkang',
			'L & T',
			'GRIPTON',
			'HIOKI',
			'FLUKE',
			'FLAIR',
			'EXTECH',
			'Multi metals',
			'Roman',
			'Tenaris',
			'Erndtebruecker Eisenwerk',
			'Eisenbau Kramer',
			'Seah Steel',
			'Zhejiang',
			'Schulz',
			'Tubacex Tubos',
			'Inoxtech',
			'Erne Fittings',
			'Sungkwang',
			'Awaji',
			'Mega',
			'Delcorte',
			'OME Metallurgica Erbese',
			'KVC',
			'Valvitalia',
			'Ace.',
			'CROSBY',
			'DILLON',
			'Vyrtych ',
			'Swisslok',
			'Sealfast',
			'QLight',
			'Patlite',
			'DIS',
			'Schaefer',
			'Pro-Vent',
			'Promist',
			'Marathon',
			'Euramco',
			'Dulux',
			'Cool Space',
			'Coppus',
			'Beck Air',
			'Ventilation',
			'Zollner',
			'TF-Cable',
			'Tormin',
			'Samcom',
			'Krempel',
			'Keskom',
			'Francis',
			'Dose',
			'Boddingtons',
			'Aqua Idea',
			'Aplei',
			'Poxytech',
			'IPM',
			'Feeleng',
			'FBV',
			'Densin',
			'Threebond',
			'Verisafe',
			'Teamtec',
			'Reflex Marine',
			'Pro-V',
			'Pro-Rope',
			'BLACOH',
			'Inter Marco',
			'Uni coupling',
			'BOSTIK',
			'DAYCO',
			'SUPERFLO',
			'TRICOFLEX',
			'Arcelor Mittal',
			'JC VALVES',
			'THERMO CABLES',
			'ADVANCE VALVES',
			'BALSTON',
			'Hubbell',
			'REVALVE',
			'salem stainless steels suppliers Pvt Ltd',
			'CMP',
			'Oliver',
			'ZANDER',
			'VELCON',
			'SHARPE',
			'WESTLOCK',
			'KECKLEY',
			'Salem Stainless Steel',
			'GEORGIN',
			'GULFTECH',
			'General Instruments',
			'NEWAY',
			'Goma',
			'valcrom',
			'CASTROL',
			'PEMTECH',
			'SECURE TOOLS',
			'QUAKER HOUGHTON',
			'ABOUTBLU',
			'PANTHER',
			'HOSEBUN',
			'UVEX',
			'MORSE STARRET',
			'MECHANIX WEAR',
			'OTECO',
			'HOWARD LEIGHT',
			'ERICSON',
			'LEWIS',
			'MALIN',
			'LUFKIN',
			'FABENCO',
			'DEMCO',
			'CONTENENTAL',
			'BPC',
			'GROSBY',
			'BESTOLIFE',
			'GWS',
			'WASCO',
			'Al Shoumoukh',
			'PROTEGO',
			'Ralson',
			'Sierra',
			'Flir',
			'Malema',
			'Tecfluid',
			'Calex',
			'Mid-west',
			'Dual_snap',
			'Ametek',
			'Switzer',
			'Mitutoyo',
			'Kyowa',
			'Laurel',
			'Infos',
			'Reotemp',
			'Mensor',
			'Ashcroft',
			'Dh Budenberg',
			'walkerbolt',
			'Ameribolt',
			'ADPICO',
			'Lonestar',
			'Chromalox',
			'Megan',
			'Hy-lok',
			'Al Afaq',
			'Pfeifer',
			'CEAG',
			'FATI',
			'NUHAS OMAN',
			'SOFAMEL',
			'DENORA',
			'MEGALITE',
			'HAVI',
			'2M KABLO',
			'LESER',
			'VSI',
			'Check Point',
			'ASAHI',
			'WIDOS',
			'Agruair',
			'Doyma',
			'AGRU',
			'AutoTork',
			'Blakeborough',
			'BDK',
			'Batley Valve',
			'WEMCO',
			'Gabbioneta Pumps',
			'Gopani',
			'PIPELINE TECHNIQUE',
			'SEW',
			'AGIRA',
			'EEC',
			'APLISENS',
			'MASCOT',
			'ALTIFORT',
			'VTS',
			'GPC',
			'GILMORE',
			'SILVERTECH',
			'MAGWELL',
			'ALDERLEY',
			'AUTROL',
			'LIWA',
			'TES',
			'IKM',
			'VALVTECHOLOGIES',
			'samson',
			'SOR',
			'SPX',
			'PFF',
			'Aucerna',
			'Galvacoat',
			'Daehan',
			'Autelec',
			'Enersys',
			'MGG',
			'PROCLAD',
			'Fabtech',
			'Emirates Steels',
			'Flexitallic',
			'SEPFLUTECH',
			'BS & B',
			'SHREE STEELS',
			'BKN',
			'BENKAN',
			'METALFAR',
			'ERNEFITTINGS',
			'TK CORPORATION',
			'MELESI',
			'CHECKPOINT',
			'GENERAL CABLE',
			'AOI',
			'Lloyds',
			'MIR valve',
			'Endress+Hauser',
			'KSB',
			'JVS ENGINEERS',
			'HIT VALVE',
			'ANGLO EASTERN',
			'KEI Industries',
			'EXCEN',
			'E-ONE',
			'CAMUNACAVI / LAPP CABLES',
			'ROSEMOUNT',
			'FITOK GMBH',
			'VERSATECH',
			'FLUIDTECH VALVES',
			'BUDENBERG',
			'SIMPLEX',
			'KILLARK',
			'METERING SOLUTIONS',
			'OMRON',
			'ROVATTI POMPE',
			'SIEMAG',
			'ENERTOK',
			'AEROVOX',
			'YANGZHOU',
			'Estruagua',
			'ASTURI',
			'TKF',
			'GM INTERNATIONAL',
			'Pressure Products',
			'DELGA SA',
			'YOUNGTECH',
			'Jumo GmbH Co',
			'PROMETHEUS S.R.L.BALEM',
			'VAMIEN DE ESPANA S.A.',
			'MIL',
			'Cashco Inc',
			'ZWICK',
			'ROTORK',
			'ALCATRAZ',
			'FLUOROSEAL',
			'KORVET',
			'AEDKOM',
			'ODDESSE',
			'IMBIL',
			'AKFEL',
			'FAIRCHILD',
			'SOLDO',
			'TRIOL',
			'PNC',
			'SHAWNDRA',
			'EFFEBI',
			'SAUDI PIPE SYSTEMS COMPANY (SPS)',
			'Libbenga Staalbouw BV',
			'RAE',
			'NDB',
			'MOREHOUSE',
			'KYORITSU',
			'KRM CORPORATION',
			'KESTREL',
			'ISA',
			'CORDEX',
			'CIRUS',
			'BW TECHNOLOGIES',
			'BAUR',
			'AMPROBE',
			'EMS',
			'SCHOELLERBLECKMANN',
			'SALEM',
			'BOTHWELL',
			'MEGA ',
			'BEBITZ',
			'ACERINOX',
			'COLUMBUS',
			'Nippon Steel & Sumitomo Metal Corporation NSSC',
			'Salzgitter Mannesmann',
			'Thai Benkan',
			'SANYO SPECIAL STEEL',
			'APERAM',
			'BUTTING',
			'GTOKHEIM',
			'USVT',
			'SEETRU',
			'SATAM',
			'RUTHLEE',
			'NUOVA MA NA',
			'Espuna',
			'Exide',
			'Petro Industrial',
			'Dixon Valve',
			'GS Entec',
			'Karl Storz',
			'Circor',
			'Gutteling',
			'Alfagomma',
			'ACTION',
			'SFG',
			'Walworth',
			'Technofit',
			'Perfect international',
			'SPM',
			'ASCO FILTRI',
			'AIMS',
			'ADSO',
			'NETCONTROL',
			'CCC',
			'Howden',
			'Cleveland cables',
			'Duke',
			'Delta',
			'EVERSENDAI',
			'TECHIMP',
			'JAQUET',
			'Emphor',
			'interkab',
			'sundyne',
			'Trimteck',
			'TMEIC',
			'TUV',
			'WEG',
			'Technical parts',
			'Nirmal',
			'Ralston Instruments',
			'CVS Controls',
			'Custom Control Sensors',
			'ProvibTech',
			'Mercer',
			'Hoffer',
			'Rototherm',
			'IMI Maxseal',
			'EEW',
			'High Pressure Instruments',
			'JET-FLOW',
			'LIFTON',
			'MBM',
			'Bernard Controls',
			'FCT',
			'Elfor Controls',
			'Hopkinsons',
			'Tricentric',
			'Sarasin',
			'Floway',
			'PRESSBOLT',
			'PRYSMIAN CABLES',
			'DRAKA CABLES',
			'Okazaki',
			'Netsafety',
			'Imtech',
			'Finetubes',
			'Biffi',
			'ELECTROMECH',
			'Waukesha Cherry-Burrell',
			'Vokes Series',
			'Tigerholm Series',
			'M&J Valve',
			'Lightnin',
			'Johnson Pump',
			'Jemaco',
			'Hytec',
			'Hydraulic Technologies',
			'Hankison',
			'Gerstenberg Schroder',
			'Dollinger',
			'Deltech',
			'Delair',
			'Copes-Vulcan',
			'Bran+Luebbe',
			'ClydeUnion',
			'Bolting Systems',
			'APV',
			'Anhydro',
			'Airpel Series',
			'Tozzi Sud',
			'Oil States',
			'Pietro Fiorentini',
			'Paladon',
			'DBMSC',
			'Sandiego',
			'AGL',
			'FITOK',
			'Intertek',
			'Petrasco',
			'Thunder',
			'IEOSS',
			'FASTTRACK',
			'Unisteel',
			'Gulf Mechatronics',
			'Shulz Fittings',
			'Viar',
			'REXNORD',
			'TALIS',
			'MF Fastener',
			'Brightech',
			'Flotek',
			'AngloEastern',
			'MIL KSB',
			'SOUTHLAND SENSING',
			'VALPRESS',
			'SPRIANO',
			'MBA',
			'ALPHA MOISTURE',
			'FAURE HERMAN',
			'TM TECNOMATIC',
			'HKS Prozesstechnik',
			'Arcair',
			'Stoody',
			'Tweco',
			'Thermal Dynamics',
			'GCE',
			'Exaton',
			'TurboTorch',
			'RPS',
			'Kelton',
			'HP well screen',
			'Halliburton',
			'Matrix',
			'Hydratight',
			'Continental Disc Corporation',
			'Stewarts',
			'Olympus',
			'John Crane',
			'Curtiss Wright',
			'Carrier',
			'Ergil',
			'Zener',
			'Fluid',
			'Flexiflo',
			'Euroblast',
			'VEETECH',
			'Modulevel',
			'Brooks',
			'AP tech',
			'Geo-Chem',
			'Ariel',
			'Cavicel',
			'Cornerstone',
			'Marapco',
			'Trinasolar',
			'SES',
			'ICON',
			'Grand Premier',
			'Rexel',
			'WABCO',
			'Globe Air',
			'MX SRL',
			'HILTI',
			'Nexalloy',
			'Laser',
			'Kurt Haufe',
			'Gazcut',
			'Miller',
			'Druck',
			'CP',
			'hydratron',
			'ESCO',
			'Ontime',
			'DSR',
			'GT',
			'EMDAD',
			'ELETTROTEK',
			'Consolido',
			'Dunapack',
			'Dunapol',
			'Corafoam',
			'Dulam',
			'DEXTER',
			'Corrdata',
			'CYLINGAS',
			'Corrater',
			'Corrosometer',
			'Nivus',
			'Aqseptence group',
			'Cobot',
			'Purolite',
			'Wave cyber',
			'Filternox',
			'Cansco',
			'Carbomastic',
			'Carboguard',
			'Bitumastic',
			'Carboline',
			'Carbotherm',
			'Carbothane',
			'Burckhardt',
			'Daly',
			'Bardot',
			'Link-Seal',
			'Evolution',
			'Mecton',
			'RUHRPUMPEN',
			'Trane',
			'PCM',
			'Gerab',
			'Oglaend',
			'DME Prolink',
			'Pepperl+fuchs',
			'Dinco',
			'Al Nimr',
			'Kelvion',
			'Maric',
			'kalikund',
			'VESTA',
			'ALEMITE',
			'Zulfi',
			'Rocol',
			'SIGS',
			'Nimax',
			'JohnCrane',
			'Hydro',
			'FTE',
			'Drilltech',
			'Clark-Reliance',
			'DBMT',
			'Time',
			'Fleetguard',
			'RBV',
			'ASP',
			'Boffin',
			'Bridon',
			'AGE',
			'Benex',
			'Stel',
			'YES',
			'Alfra',
			'Cidan',
			'Adira',
			'AAVI',
			'NS',
			'Barton',
			'Accurate Edge',
			'Elsewedy',
			'Plymovent',
			'Ensitech',
			'Optrel',
			'Siegmund',
			'Motortronics',
			'Airgas',
			'Corroline',
			'METZ',
			'Belzona',
			'Drymix',
			'Corrotech',
			'Corrosol',
			'CSS',
			'Marechal',
			'Griswold',
			'Blackmer',
			'Abaque',
			'Ebsray',
			'Neptune',
			'Mouvex',
			'Leading Edge',
			'HMS',
			'STE',
			'OMB',
			'Dimet',
			'M-Rak',
			'Mastercote',
			'Moflash',
			'Intertec',
			'Bentler',
			'JULMA Piping',
			'Jiuli',
			'INTERPIPE',
			'Marjan',
			'Najmt',
			'Trans',
			'A-Elesco',
			'CalCon',
			'Tecsis',
			'Badotherm',
			'CAPE',
			'Al Miqat',
			'PPC',
			'Sichem',
			'EcoTech',
			'Aquaness',
			'JFE',
			'ARAS',
			'ChemDrill',
			'Al Arkan',
			'Energen',
			'STAYER',
			'AFH Tools',
			'Hans',
			'AL Majjarah',
			'Britool',
			'Omega',
			'HAFU',
			'Ruko',
			'Matador',
			'BoltMaster',
			'Hunter',
			'Dormer',
			'ESMA',
			'Faquihi',
			'Globe United',
			'Mexxor',
			'Solas Marine',
			'ADOR',
			'CamStar',
			'EWM',
			'Fronius',
			'TransCrescent',
			'TechnoMax',
			'Vanleeuwen',
			'Hart',
			'Edgen Murray',
			'SNP',
			'Jord',
			'Dillinger',
			'FleetLine Shipping',
			'Tech Hard',
			'GPI',
			'Solar',
			'Expeditors',
			'Online valves',
			'Metalfab',
			'Tiger Offshore',
			'Sulzer',
			'Flowfit',
			'Hotline Steel',
			'Hadaf',
			'Grayloc',
			'HBT',
			'InoTech',
			'JSS Pipes',
			'Kurvers',
			'Perfect Engineering',
			'MHT',
			'Saga PCE',
			'Mazrui',
			'Red-D-Arc',
			'BAC',
			'Bonetti',
			'Master valve',
			'Klinger Fluid Control',
			'Albany Pumps',
			'FKM',
			'UNP POLYVALVES',
			'HORA',
			'DK-LOK',
			'YTC',
			'Burket',
			'Q-Aviation',
			'Bernard',
			'HYDRAULIC INTERNATIONAL',
			'Norbar',
			'Oilsafe',
			'Vessel',
			'Izumi',
			'Magnetrol',
			'SIFAM TINSLEY',
			'MATHERNE',
			'Pangborn',
			'DALGAKIRAN',
			'Eurogrit BV',
			'AbraTough',
			'Sibelco',
			'Uniquecoat',
			'Rezontech',
			'FLOWROX',
			'Yamada',
			'Volumec',
			'TSERVE',
			'TMK',
			'TaegeTec',
			'Pune Techtrol',
			'PRYOR',
			'ProTech',
			'MOHSIN',
			'TIBO',
			'MidFiled',
			'Kokem',
			'Lancaster',
			'KITZ',
			'HATTERSLEY',
			'CIOE',
			'ConstroMech',
			'Brady',
			'MaxTorq',
			'Buhlmann',
			'Al Mazroui',
			'AARON INTL',
			'TATA',
			'Shell',
			'Dow',
			'ATOTECH',
			'Eisenblaetter',
			'Karbosan',
			'Lafonte',
			'PANOPLY',
			'AD Systems',
			'Petrochem',
			'C&S Electric',
			'GE',
			'KOP',
			'EK Heat',
			'NOV',
			'RIGServe',
			'Katch Kan',
			'Jorin UK',
			'Basier Electirc',
			'Ducorr',
			'QTS',
			'AGC',
			'ADC',
			'SPECTRA',
			'Delphian Corp',
			'Source One',
			'Al Mansoori',
			'Verope',
			'Agar',
			'LumaSenses',
			'Land',
			'AIR',
			'Rotoflow',
			'Camlok',
			'ATTA',
			'Al Hamad',
			'Adyard',
			'Cooper',
			'Globex',
			'ABO valves',
			'FIRE EATER',
			'Marioff',
			'STANG',
			'NEURUPPIN',
			'ARAR',
			'Atarfil',
			'Eurogulf',
			'Federal',
			'Aertssen',
			'ET',
			'Robuschi',
			'Nash',
			'Emirates',
			'Hayward Tyler',
			'VAG',
			'TC',
			'Valbruna',
			'Hauff technik',
			'Experts',
			'IPP pumps',
			'BAND-IT',
			'Gardner Denver',
			'AUMA',
			'Dutco',
			'HENKEL LOCTITE',
			'MTS',
			'MSA Helmets',
			'Jsafe',
			'LEAVES',
			'CATU Beest',
			'Pewag',
			'Safety JOGGER',
			'Respirex',
			'Thermofisher',
			'McWane',
			'Aloyco',
			'REDA',
			'ACME',
			'Corrotherm',
			'BROGAN',
			'MSA',
			'MTL',
			'Refrigi Wear',
			'RECOM',
			'LubeTech',
			'Enware',
			'ION',
			'Wallace Cameron',
			'JUTEC',
			'JoBird',
			'Centurion',
			'ABCO',
			'Eska',
			'Cederroth',
			'Maxell',
			'Flame Safe',
			'Comfy',
			'Riley',
			'Haws',
			'Techtion',
			'A One',
			'SAFE-T-GARD',
			'Patrick',
			'Moly Lubricants',
			'Consilium',
			'SCC',
			'Frontier',
			'MIDAS',
			'Valpro',
			'Ninja',
			'Palmy',
			'SYI Foundry',
			'Salma Safety',
			'Maddalena',
			'Galloppini',
			'HUWA',
			'KED Brooke',
			'MK',
			'Speedsafety',
			'Brannan',
			'Record Power',
			'Maxima',
			'Wemaro',
			'PMS Thaico',
			'Sure Power',
			'Bahco',
			'Venitex',
			'Akron',
			'RANGERS',
			'TEKAB',
			'Spark',
			'SHARCAB',
			'Volex',
			'British General',
			'Weber Hydraulic',
			'GAV',
			'Hanson',
			'GLOOR Bros',
			'A.C.S Canada',
			'New Cosmos',
			'NORTH',
			'Komyo Rikagaku kogyo japan',
			'Ingersoll Rand',
			'Superior',
			'Al Nahda',
			'VAN BEEST',
			'Interope',
			'Al Bahri',
			'Al Hana Oilfield',
			'AVK',
			'Emirates Robotics',
			'Syed contracting',
			'TTV',
			'ACTREG',
			'DSI Valve',
			'PBV valve',
			'TURCK',
			'RAY Intl',
			'DECO',
			'NEECO',
			'BRDR Christensen',
			'Streamflo',
			'VELAN',
			'ASIABOLTS',
			'Versa',
			'NUOVA FIMA',
			'WARTSILLA',
			'Skintop',
			'Fleximark',
			'Silvyn',
			'Hilong',
			'Liftek',
			'Horizon',
			'Integrated chemicals',
			'Olflex',
			'Novaform',
			'Unitronic',
			'hicoTEC',
			'Flowline',
			'Epic',
			'Gallopstar',
			'Viscoplex',
			'Kalcat',
			'GBC',
			'Gowell',
			'DYNACOLL',
			'FRF',
			'Evonik',
			'Taicros',
			'Aventus',
			'Ashtead',
			'Alesta',
			'Amphenol',
			'Metalyst',
			'Catylen',
			'Hitronic',
			'Alpharex',
			'PURETECH',
			'Kalhour',
			'AMI',
			'RNG',
			'BALTIC',
			'SABELATRANS',
			'Freelance',
			'ABN',
			'HAVEN',
			'Inchcape',
			'VGL',
			'Rapid',
			'GeneralPetroleum',
			'Nutec',
			'LAME',
			'APCO',
			'Petron',
			'Foresight',
			'MAGNATECH',
			'MADGETECH',
			'Roots',
			'ONWELL',
			'EVE',
			'Blue Ribbon',
			'Petromar',
			'SPIE',
			'LINKS',
			'Metro',
			'Mother Engineering',
			'Team skill',
			'Yerevan',
			'York',
			'Al Karmel',
			'Tag-it',
			'Hunk',
			'Oryx',
			'PSI',
			'Lindapter',
			'G-Force',
			'Modulift',
			'MuvTons',
			'SRS',
			'LiftinGear',
			'Al Etimad',
			'Sheet Metal',
			'AdvancedWay',
			'Gestra',
			'Limitorque',
			'Jiskoot',
			'Bifold',
			'BOISSET & CIE BC SA',
			'Elixir',
			'Atex',
			'Meisco',
			'Graco',
			'MEM',
			'Marcap',
			'Mayekawa',
			'Mammoet',
			'Martrade',
			'Sentry',
			'Motive',
			'Mintra',
			'Salama',
			'OGS',
			'Next',
			'Nemochem',
			'Nico',
			'BILCO',
			'Giant',
			'ELMEX',
			'Maruchi',
			'HADLEY',
			'PERMA PLUG',
			'AN WALLIS',
			'KLAUKE',
			'PCE',
			'AOISC',
			'CLICK',
			'YESHA',
			'TOP CABLE',
			'RAXTON',
			'HAWKE',
			'EMIRATES WESTERN',
			'AquaJets',
			'PETRO GEAR',
			'RED SOIL',
			'Al Jazeera',
			'DANEM',
			'Kessab',
			'SALWA',
			'ACDelco',
			'Solite',
			'SEBANG',
			'Hankook',
			'Sumitomo',
			'MICHELIN',
			'Firestone',
			'Bridgestone',
			'GRAA',
			'CALTEX',
			'Dextrol',
			'GulfStar',
			'Rouge',
			'Global Pageant',
			'IndoGulf',
			'Hartford',
			'GMES',
			'TUBESTAR',
			'Aces',
			'Inspecta',
			'Technical Inspection Bureau',
			'Korean Techno',
			'Quest Integrity',
			'SEACORR',
			'Sievert',
			'Blackbelt',
			'Kaddas',
			'NTN',
			'SJS',
			'Montero',
			'Stucchi',
			'TPS',
			'SEKWANG',
			'Dutron',
			'Uni-Flex',
			'Promat',
			'Manuli',
			'Raycom',
			'RCG',
			'RAMCO',
			'Restrata',
			'Roctec',
			'Peronipompe',
			'PPG',
			'OSC',
			'Power plus cable',
			'Schlemmer',
			'Accuver',
			'Rolon',
			'Xpert decor',
			'Peramer',
			'WAROM',
			'Alinox',
			'RDI',
			'UMC',
			'ACADIANA',
			'MUD KING',
			'HUWE',
			'Keystone',
			'HI KALIBRE',
			'Shaksy',
			'Tecninox',
			'TERASAKI',
			'PRESYS',
			'Kanomax',
			'PTPA Valves',
			'Teekay',
			'SENSFIB',
			'Delitek',
			'RWO',
			'Precision',
			'PETROL RACCORD',
			'Metallic Bolts',
			'FireHut',
			'DET-TRONICS',
			'C-Tec',
			'Ampac',
			'Dremel',
			'BFGoodrich',
			'TIGAR',
			'Valeo',
			'KNORR-BREMSE',
			'ZEXEL',
			'CYCLO',
			'ASNU',
			'WINGROU',
			'Al Mutqan',
			'CJC',
			'Galaxy',
			'Kendall',
			'RSK',
			'JetPro',
			'JGun',
			'STEALTH',
			'Edge',
			'MXT',
			'Avanti',
			'Simultorc',
			'Nexus',
			'HUSQVARNA',
			'STIHL',
			'DustControl',
			'C.C.E',
			'Firestop',
			'TKK',
			'Koester &Co',
			'Al Moosawi',
			'LAIZAT',
			'BRIGHT',
			'ICE',
			'Petrocil',
			'Siirtec Nigi',
			'Bright oilfield',
			'ShineTech',
			'M-I Gulf',
			'Barracuda',
			'DIVETECH',
			'Al Faris',
			'Discovery',
			'House of Chemicals',
			'Walid Battat',
			'Prestige',
			'Kheraj',
			'WOLF',
			'Eagle USA',
			'DAWG',
			'Storz',
			'MAGMEX',
			'BRK',
			'HAMMAR',
			'VSG',
			'Tritex',
			'Huatec',
			'Niton',
			'Glassco',
			'Traverse',
			'SIEMECS',
			'MISPAH',
			'ABS',
			'NDT CCS',
			'NSCC',
			'Capital Surverys',
			'BYRNE',
			'Spira Power',
			'Hutmen',
			'Driconeq',
			'Algas',
			'A+R',
			'Gasarc',
			'Lapesa',
			'Hanwei',
			'Sitex',
			'Petrosafe',
			'Happyway',
			'Unigaz',
			'AL FANAR',
			'Deck Equipments',
			'SafeTech',
			'Dredge',
			'Glassware',
			'HAMWORTHY',
			'Saint Gobain PAM',
			'GE Druck',
			'Oldham',
			'Profile Middle East',
			'Al Ashaq',
			'DK Synergies',
			'ISTL',
			'Sanshin',
			'AMRO',
			'Global Maritime',
			'Wellpro',
			'JMP',
			'Wesco',
			'Windlass',
			'Powrquik',
			'Griffin',
			'Marsol',
			'Woodserv',
			'Wollschlager',
			'Trans Asia',
			'Brenntag',
			'Total Safety',
			'AARTI',
			'Flowtech',
			'Ventil',
			'Samjoo',
			'MLab',
			'HENGDA',
			'HMSA',
			'THOMAS & BETTS',
			'Furukawa',
			'SEOUL',
			'HDE',
			'Wiska',
			'Vija',
			'ZMI',
			'Tendeka',
			'EEKELS',
			'Hydroster',
			'THL',
			'Oiltanking',
			'CRC-EVANS',
			'Statron',
			'Winteb',
			'Startech',
			'Sunrise',
			'Siad',
			'SMS',
			'Sigma',
			'Smith Gulf',
			'Specialized',
			'Flowflex',
			'Appleton',
			'SAB',
			'Thomas',
			'Siirtec',
			'Safelift',
			'Lauris',
			'Scale',
			'SAMA',
			'Sea Gulf',
			'Soosung',
			'Diamond cutting',
			'DelmaCoat',
			'IDEA Star',
			'Al Mayasa',
			'Deep Sea',
			'Anamet',
			'GOIS',
			'Arabian Bureau',
			'GQCS',
			'TIB',
			'Hartford',
			'SITEC',
			'ADNOC',
			'SERGAS',
			'IMS',
			'High scope',
			'EMIRATES TECHNOTRADE',
			'Karcher',
			'HY-TWIN',
			'COMMSCOPE',
			'ANDREW',
			'Bericacavi',
			'Analog Devices',
			'ebm-papst',
			'MICROCHIP',
			'Molex',
			'Panasonic',
			'Teufelberger',
			'Anest Iwata',
			'TEC Containers',
			'James Walker',
			'CORROSEAL',
			'Wade',
			'Adamallys',
			'CON-JOINT',
			'NFM',
			'INMA',
			'Genoyer',
			'Golden Screw',
			'Petroyas',
			'FILL-RITE',
			'Liquid Controls',
			'Total Control Systems',
			'Midco',
			'Novaflex',
			'Reel Craft',
			'Mcard',
			'Gasso',
			'Betts',
			'MVT',
			'Jeddah Cables',
			'NCI',
			'Captain',
			'Himsen',
			'Al Banoosh',
			'HOC',
			'MAZURCZAK',
			'Al Taher',
			'MEFIAG',
			'Karhosan',
			'VALE INCO',
			'Progressive',
			'MASTECH',
			'GSSC',
			'MCM-FieldCore',
			'SSI',
			'Al Shola',
			'EKKO',
			'Turbo Lifting',
			'H.Albert',
			'WISMAR',
			'GoodWill',
			'Transafe',
			'BECKHOFF',
			'Continental',
			'Sarsan',
			'Hatz',
			'Triple Fast',
			'Al Hakim',
			'Goltens',
			'Serco Energy',
			'LVF',
			'Tecnoforge',
			'Rapisarda',
			'Flextraco',
			'Shintech',
			'Oloham',
			'Lamprell',
			'Al Fariz',
			'Dar Al Zain',
			'NCC',
			'EMCC',
			'AHM',
			'Avatar',
			'PRIME',
			'JTS',
			'PPM',
			'RSS',
			'Conmix',
			'Accurate',
			'OnTides',
			'B & B',
			'ATG',
			'Durco',
			'Ideal',
			'Chess',
			'DBB',
			'Perfactive',
			'MEGARME',
			'Amwaj',
			'Global',
			'Santafede',
			'Master tech',
			'Proflow',
			'Mitas',
			'S & T',
			'Macchi',
			'Bassi',
			'Core',
			'Tokyo',
			'Pikotek',
			'Sideco',
			'Logistics',
			'SITINDUSTRIE VALVE',
			'IN-LINE',
			'OCS',
			'Brush',
			'Magwen',
			'Rotex',
			'Euro2000',
			'MECI',
			'STAR Energy',
			'GRP',
			'Astec',
			'Micro Motion',
			'IMI Orton',
			'IMI CCI',
			'Advanced Insulation',
			'Shafer',
			'Pan-Continental',
			'Indo Carb',
			'Valbart',
			'Interseal',
			'Al Ashfaq',
			'ADGHAL',
			'Larson',
			'IMI B&R',
			'IMI STI',
			'IMI Truflo',
			'Delta bar',
			'DEE',
			'DCN',
			'Data track',
			'Delta wye',
			'DMI',
			'Abu Dhabi construction',
			'Demag',
			'PROOFEX',
			'THIOFLEX',
			'DEKGUARD',
			'GALVASHIELD',
			'CONPLAST',
			'FOSROC',
			'NITOTILE',
			'Mathews & Yeats',
			'Protectoseal',
			'Suntech',
			'Al Ghaith',
			'Robust',
			'Techmaflex',
			'Al Bawardi',
			'Bajaj',
			'Safar',
			'AL ARABIAH',
			'Sellstorm',
			'AIL',
			'Kong',
			'Nemesis',
			'Transmille',
			'Raytech',
			'Phenix Technologies',
			'AIE',
			'Aqua Diving',
			'Anixter',
			'Delta Trak',
			'Scarlet',
			'Aftec',
			'Ecotherm',
			'Franklin Electric',
			'OMG',
			'Aurora',
			'Landa',
			'ACWA',
			'FPT',
			'Ringtail',
			'Mettler toledo',
			'ASBR',
			'JM canty',
			'AALBORG',
			'Rose systemtechnik',
			'Accent',
			'MUC',
			'Mirdif',
			'Minova',
			'MICODA',
			'TEXSTEAM',
			'ENTECH',
			'GROVE Valves',
			'MESC',
			'Masters Crane',
			'MDMC',
			'Mach Air Cargo',
			'JMS',
			'BRODIE',
			'MSYSTEM',
			'Leaders Oilfield',
			'Khalidia',
			'Kaeser',
			'Frick',
			'Nitta',
			'Hutchinson',
			'Megadyne',
			'Sentrix',
			'Cook',
			'Static-Pac',
			'Moppet',
			'CASP',
			'Manley',
			'Chemtrols',
			'CEVA',
			'CATALYST',
			'Canusacoat',
			'Canusaseal',
			'HBE',
			'Factory Grade',
			'CEEM',
			'Boma',
			'BWS',
			'Trinity Holdings',
			'Drasic',
			'W Abrasives',
			'Munkebo',
			'Trelawny',
			'Frank',
			'CLEMCO',
			'Barloworld',
			'ATI',
			'Aswan',
			'Aries',
			'Rexway',
			'AOSS',
			'Revalco',
			'Raychem',
			'Additel',
			'Anaum',
			'Flexicon',
			'FGC',
			'Chalmit Lighting',
			'BESANTEK',
			'Alpha Star',
			'ALMAR',
			'PILS',
			'Apex',
			'Walsall',
			'FZV',
			'Baliga',
			'Al Muftah',
			'Al Moherbie',
			'SIKA',
			'NETZSCH',
			'Eastman',
			'Anza',
			'Cranden Diamond',
			'WSL',
			'Stoner',
			'SE Tylose',
			'AOC',
			'CLARIANT',
			'OCV',
			'INEOS',
			'BYK',
			'Liftech',
			'Alitaliya',
			'American Block',
			'Rothenberger',
			'Airblast',
			'ACT',
			'Blastrite Gulf',
			'Blue Metal',
			'Omgrit',
			'Profab',
			'Modec',
			'Mac',
			'Reid',
			'SPA',
			'Volta',
			'Thern',
			'TQT',
			'Unique',
			'NITOFLOR',
			'Al Robban',
			'Condtrol',
			'DeltaTrak',
			'DV Power',
			'Skycom',
			'VON',
			'Arabian Calibration',
			'Ataico',
			'Metallisation',
			'Scar-Guard',
			'Corporate Shipping',
			'Cudd',
			'Monicon',
			'Stork',
			'Freight works',
			'GBA',
			'Extol',
			'Fendercare',
			'EMI',
			'Falcor',
			'Flowtools',
			'Eurochem',
			'Intrac',
			'PM piping',
			'GMP',
			'Eppi',
			'Equinox',
			'SOCONORD',
			'Elite',
			'E.H. WACHS',
			'Power centre',
			'ALL METALS',
			'AL RASHEEDIAH',
			'AL QASER',
			'AL MUSTWA',
			'AL MAZMI',
			'ELEKTRA',
			'HENSEL',
			'AL FAHIDI',
			'AL EMAD',
			'AL DHAFRA',
			'AL BOSHIA',
			'AL BATOOL',
			'Al Bahr',
			'AGILITY',
			'ACORN',
			'SHARJAH OXYGEN',
			'AA SERVICES',
			'Vego',
			'Powertech',
			'CT Power',
			'Taillift',
			'Technical Inspection',
			'Baldwin',
			'Fire-Hawks',
			'TKH',
			'Servochem',
			'Sebchem',
			'Scientific Drilling',
			'Scantech',
			'Spilfyter',
			'Ultratech',
			'Simple Green',
			'Inder',
			'STC',
			'Gulf-O-Flex',
			'Ferolite',
			'Manho',
			'Stallion',
			'Ferodo',
			'Kiwes',
			'JURID',
			'Simatec',
			'MOVE IT',
			'Donaldson',
			'Airman',
			'THK',
			'FireMiks',
			'NAK',
			'SCHWEGMANN',
			'CCP',
			'Eternal',
			'DBC',
			'Schulke',
			'Organikkimiya',
			'Chemours',
			'FYH',
			'Procal',
			'Petrostem',
			'Petrolcom',
			'Loadtec',
			'Marit',
			'Panalpina',
			'KVM',
			'Simpson-Strongtie',
			'Orkot',
			'Ironclad',
			'Orient',
			'Forum',
			'ARFLU',
			'Oasis Pumps',
			'NOVA',
			'Niedax',
			'Napier',
			'WENCON',
			'Hedemora',
			'Resimac',
			'Doen',
			'Daniamant',
			'Cleanship',
			'ALLSAFE',
			'Fong Kee',
			'Neilchem',
			'BASEC',
			'ISAL',
			'KIT Oil & Gas',
			'LOT',
			'PENTAGON',
			'PEPS',
			'SERVTECH',
			'SulTech',
			'Rentech',
			'Calorex',
			'Gulf cobla',
			'Hellmann',
			'GAC',
			'Haytak',
			'Heatec',
			'George Taylor',
			'GEC',
			'Gersan',
			'GMMOSTECH',
			'ITECO',
			'Innova',
			'ISEAS',
			'IFC',
			'IMA',
			'ICS',
			'General',
			'IER',
			'Hunting',
			'Bijur',
			'Howco',
			'Kawasaki',
			'IBN',
			'Dakota',
			'Danatronics',
			'CYGNUS',
			'Carestream',
			'GLOBELINK',
			'GLENCORE',
			'GHANTOOT',
			'GAMMA',
			'G.O.P.E',
			'FUJAIRAH',
			'JONESCO',
			'RADIAGREEN',
			'ESP',
			'YOKOHAMA',
			'LAMOR',
			'FAST FORWARD GROUP',
			'AWG',
			'FUGRO',
			'FREIGHT SYSTEMS',
			'INTERSEL',
			'INTERO',
			'ITS',
			'INTOP',
			'IIE',
			'MACOGA',
			'INMARCO',
			'IIG GROUP',
			'BIJUR DELIMON',
			'DMH',
			'Brevini',
			'Salami',
			'MP Filtri',
			'Hydraforce',
			'TECO',
			'Rice HYDRO',
			'PIHASA',
			'Larzep',
			'CERTUSS',
			'HRS Funke',
			'Gulf Metal',
			'Grand Technical Service',
			'MAXTUBE',
			'Gogas',
			'NOVO',
			'ZETEC',
			'Masibus',
			'Marck',
			'MARITRONICS',
			'Vetter',
			'Lukas',
			'S-gard',
			'MARAMI METAL',
			'Husky',
			'COEN',
			'Pall',
			'Arca',
			'MACGREGOR',
			'Lloyds Register',
			'LAMNALCO',
			'KCA DEUTAG',
			'KAEFER',
			'ISMAT',
			'Seatrail',
			'SCAN POWER',
			'FIREX',
			'RAJ METAL',
			'CALGAZ',
			'RHS GROUP',
			'PRO CARGO',
			'Power Economy',
			'Petro Tek',
			'Pearl',
			'Overseas',
			'OSS FZC',
			'NO SHOCK',
			'Penta Global',
			'Kingroy',
			'Ocean',
			'Mefab',
			'SUD-CHEME',
			'Innospec',
			'ROSEN',
			'US PIPE',
			'Iseki',
			'PARKBURN',
			'BAAB',
			'RESOLCO',
			'OGASCO',
			'FORT',
			'Marellimotori',
			'Lafert',
			'Calpeda',
			'MEDISKY',
			'MEI CLADDING',
			'Arimar',
			'Nabhan',
			'Irpco',
			'EagleBurgmann',
			'DITCHWITCH',
			'Dafoos',
			'BAF VALVES',
			'ORBINOX',
			'MOKVELD',
			'GOULDS PUMPS',
			'CTS',
			'BRIDGEWAY',
			'BlueWhale',
			'Fahlke',
			'HPI',
			'KHCK',
			'BEL VALVES',
			'ALTECH',
			'BMS',
			'Seaward',
			'AL SHAHBA',
			'Mersen',
			'NPK',
			'NITCHI',
			'EP',
			'DAESAN',
			'BEST WELDS',
			'AL HORIYA',
			'TERCOM',
			'AL HIRAH',
			'XTRONICA',
			'SAFETEC',
			'GASTEC',
			'BRANSSTORM',
			'Komatsu',
			'Caterpillar',
			'AL FATTH',
			'AKKURAT',
			'MAGNUM',
			'DEVON',
			'KIKUSUI',
			'XITRON',
			'INTERPRO SYSTEMS',
			'SIGLENT',
			'ADVANCED COMPOSITES',
			'Habasit',
			'HANSUN',
			'LEICA DISTO',
			'BRUYNZEEL',
			'ADVANCED PIPES',
			'Talustech',
			'DOTEC',
			'SCHMALZ',
			'ACEROMET',
			'ABU DHABI PIPE FACTORY',
			'Canasafe',
			'ARISON GULF',
			'GULF CRYO',
			'APT GLOBAL',
			'Webblon',
			'Silverline',
			'KLASS',
			'Tiger',
			'Allianz Marine',
			'IRWIN',
			'BETA',
			'AB VALVES',
			'Altair',
			'Marvac',
			'Marston',
			'Amal',
			'Birkett',
			'Talan',
			'Empiral',
			'Promax',
			'Tuthill',
			'Nitto Seiko',
			'Perolo',
			'Sotera',
			'TODO',
			'Scully',
			'Corken',
			'M7',
			'FKE',
			'TVS',
			'HALANI GROUP',
			'GLOBAL PETROLEUM',
			'GEODIS',
			'Fiberbond',
			'Flexstrong',
			'Flowstrong',
			'Wellstrong',
			'Lift-Jet',
			'RENOLD',
			'DODGE',
			'TORK',
			'Standard Pumps',
			'Seko',
			'Roto Fluid',
			'Mini Motor',
			'VEMAT',
			'Sumak',
			'Makim',
			'Full Blaze',
			'Bonus',
			'5M',
			'GULF OILS',
			'GREAT WATERS',
			'GRANDWELD',
			'Barboflex',
			'COME UP',
			'ALBWARDY MARINE SERVICES',
			'KOTAMINYAK',
			'RAKANNUSA',
			'CCM',
			'Swelore',
			'RSI GROUP',
			'ODFJELL',
			'AL JARSH',
			'DUMO',
			'AKZO',
			'Ecosoft',
			'NECON',
			'VIQUA',
			'CLEAN BLAST',
			'Centaur',
			'Regent',
			'Rexco',
			'Cavalier',
			'Scuta',
			'AL KHOORY',
			'AirIna',
			'Buckler',
			'Supremo',
			'GLYPTEC',
			'Aves',
			'BROWN MCFARLANE',
			'Bredero Shaw',
			'BMT',
			'MOLYKOTE',
			'PERMATEX',
			'ACHECH',
			'Mariani',
			'RMT',
			'VALVOSIDER',
			'EXTRA Co',
			'EUROLINK',
			'EMMET',
			'EMARAT MARITIME',
			'Hitec',
			'DORMAN',
			'ELIMA-MATIC',
			'Alphacor',
			'Fiberstrong',
			'FIBERMAR',
			'Wavistong',
			'FUEL TRADING',
			'CROWN',
			'ZIC',
			'LEE ENERGY SYSTEMS',
			'UNIVERSE MACHINE CORP',
			'IDC',
			'INTER GULF',
			'ISCCO',
			'Hughes',
			'HITEK OCEANIC',
			'Quattro XO',
			'Hemudur',
			'NEOGARD',
			'Hempatop',
			'TUBOSCOPE',
			'Axelson',
			'Anson',
			'AmClyde',
			'ELECON',
			'ELCOME',
			'EMSCO',
			'Kenworth',
			'Hyster',
			'JAINSON',
			'Hempaguard',
			'Hempafire Pro',
			'Hempadur',
			'Hempacore',
			'Globic',
			'Galvosil',
			'Dynamic',
			'Versiline CUI',
			'WHITE SAFETY LINE',
			'KANE',
			'Bireks',
			'SEVAL KABLO',
			'FOUNDROMETERS',
			'Goker Plast',
			'BEELE',
			'HAJI SIDDIQUE FOUNDRY',
			'Honda',
			'Nissan',
			'Toyota',
			'Exol',
			'PROBAT',
			'Ulpia Rulmenti',
			'DPI',
			'GULF WATER TREATMENT',
			'GEAP',
			'MUBARAK MARINE',
			'MIDDLE EAST SWITCHGEAR',
			'MARIDRIVE',
			'MAN',
			'LIN SCAN',
			'LIKPIN',
			'SureLift',
			'MaxLife',
			'KimLoft',
			'KINETICS',
			'KHK',
			'KENTZ',
			'RTE INTERNATIONAL',
			'Velvet',
			'Perlon',
			'Nylon',
			'Natural',
			'Bottarini',
			'NEW VISION METAL',
			'NABORS',
			'SUBSEA & MARINE SERVICES',
			'STEMCOR',
			'GM ENGINEERING',
			'Sharlu',
			'Microfiber',
			'RAMSIS',
			'QUEPET',
			'PURE WATER TECHNOLOGY',
			'POLYFAB',
			'PLASTIC POWDER COATING',
			'PETROSTAR',
			'OTIS',
			'PAOLONI',
			'FORMAT-4',
			'EDWARDS',
			'CORIMPEX',
			'Baykal',
			'Euromac',
			'STALCO',
			'AKBENO',
			'PETROGAS',
			'Arise',
			'Shinestar',
			'GRAINGER',
			'SEVEN SEAS',
			'SELECTIVE MARINE',
			'SATA',
			'OAV',
			'Melabo',
			'Fini',
			'SEAWAY',
			'SEAPORT',
			'SCHEMES',
			'SCAFFCO',
			'ZF MARINE',
			'VICTAULIC',
			'FEVISA',
			'GEMAK',
			'TECHNICAL SRL',
			'WATTS',
			'ZUBI',
			'COMEVAL',
			'UNIVERSAL TUBE & PLASTIC',
			'ZINOL',
			'UNION INDUSTRIES',
			'UNION GULF',
			'KRACHT',
			'AXIS WELL TECH',
			'TOPAZ',
			'TIDE WATER',
			'THREE STAR METAL',
			'SWIRE PACIFIC',
			'SUBSEA 7',
			'Timm',
			'Fort Valve',
			'Sontay',
			'Sara Sae',
			'SealXpert',
			'Site Technologies',
			'Phoenix controls',
			'Siverstar',
			'Southwest',
			'htl',
			'SGS',
			'Sibca',
			'Flowcon',
			'Foxboro',
			'Advanced electronics',
			'Tecumex',
			'Techno Marine',
			'TDW',
			'Stonhard',
			'Semco',
			'Pro struct',
			'SLP',
			'Wilhelmsen',
			'XS PLATFORMS',
			'Zaina',
			'Zubaidi',
			'Wadi masila',
			'Valmont',
			'Wetco',
			'WWT',
			'Wild well',
			'WAAREE',
			'UNI ARAB',
			'UEPS',
			'Universal',
			'Uruguay',
			'Bulwark FR',
			'Transfluid',
			'ARGAL',
			'TBS',
			'Turgen',
			'Twelve star',
			'Valaris',
			'Toll',
			'Twos',
			'FMB',
			'Transbulk',
			'OMAN OCEAN',
			'Advanced',
			'SHINE STAR',
			'RBR',
			'ST Eng',
			'Special Equipment',
			'SPN',
			'Valmark',
			'Fibergrate',
			'DNV',
			'Double Life Corp',
			'REED',
			'Rotronic',
			'Cast',
			'Sensaphone',
			'Ultra Ever Dry',
			'Jiangsu(ASAC)',
			'Kiswire',
			'Dong Yang',
			'Greater Cairo',
			'KITO',
			'TORC',
			'Tobee',
			'THT',
			'OAI',
			'THINKY',
			'EUROTRON',
			'TECHNE',
			'TIME ELECTRONICS',
			'WEICON',
			'caparol paints Dubai',
			'Others'
    	];
    	
    }
    
  
  

}
