<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Webpatser\Uuid\Uuid;

class Country extends Model
{
    //

    static function getCountry(){

    	return $countries = [
    		["ciso"=>"AF","code"=>"+93","country"=>"Afghanistan"],
			["ciso"=>"AL","code"=>"+355","country"=>"Albania"],
			["ciso"=>"DZ","code"=>"+213","country"=>"Algeria"],
			["ciso"=>"AD","code"=>"+376","country"=>"Andorra"],
			["ciso"=>"AO","code"=>"+244","country"=>"Angola"],
			["ciso"=>"AR","code"=>"+54","country"=>"Argentina"],
			["ciso"=>"AM","code"=>"+374","country"=>"Armenia"],
			["ciso"=>"AU","code"=>"+61","country"=>"Australia"],
			["ciso"=>"AT","code"=>"+43","country"=>"Austria"],
			["ciso"=>"AZ","code"=>"+994","country"=>"Azerbaijan"],
			["ciso"=>"BS","code"=>"+1242","country"=>"Bahamas"],
			["ciso"=>"BH","code"=>"+973","country"=>"Bahrain"],
			["ciso"=>"BD","code"=>"+880","country"=>"Bangladesh"],
			["ciso"=>"BB","code"=>"+1246","country"=>"Barbados"],
			["ciso"=>"BY","code"=>"+375","country"=>"Belarus"],
			["ciso"=>"BE","code"=>"+32","country"=>"Belgium"],
			["ciso"=>"","code"=>"+591","country"=>"Bolivia"],
			["ciso"=>"BA","code"=>"+387","country"=>"Bosnia and Herzegovina"],
			["ciso"=>"BW","code"=>"+267","country"=>"Botswana"],
			["ciso"=>"BR","code"=>"+55","country"=>"Brazil"],
			["ciso"=>"","code"=>"+673","country"=>"Brunei"],
			["ciso"=>"BG","code"=>"+359","country"=>"Bulgaria"],
			["ciso"=>"MM","code"=>"+95","country"=>"Burma"],
			["ciso"=>"BI","code"=>"+257","country"=>"Burundi"],
			["ciso"=>"KH","code"=>"+855","country"=>"Cambodia"],
			["ciso"=>"CM","code"=>"+237","country"=>"Cameroon"],
			["ciso"=>"CA","code"=>"+1","country"=>"Canada"],
			["ciso"=>"CF","code"=>"+236","country"=>"Central African Republic"],
			["ciso"=>"TD","code"=>"+235","country"=>"Chad"],
			["ciso"=>"CL","code"=>"+56","country"=>"Chile"],
			["ciso"=>"CN","code"=>"+86","country"=>"China"],
			["ciso"=>"CO","code"=>"+57","country"=>"Colombia"],
			["ciso"=>"CG","code"=>"+242","country"=>"Congo"],
			["ciso"=>"CR","code"=>"+506","country"=>"Costa Rica"],
			["ciso"=>"","code"=>"+225","country"=>"Cote d’Ivoire (Ivory Coast)"],
			["ciso"=>"HR","code"=>"+385","country"=>"Croatia"],
			["ciso"=>"CU","code"=>"+53","country"=>"Cuba"],
			["ciso"=>"CY","code"=>"+357","country"=>"Cyprus"],
			["ciso"=>"CZ","code"=>"+420","country"=>"Czech republic"],
			["ciso"=>"DK","code"=>"+45","country"=>"Denmark"],
			["ciso"=>"DJ","code"=>"+253","country"=>"Djibouti"],
			["ciso"=>"EC","code"=>"+593","country"=>"Ecuador"],
			["ciso"=>"EG","code"=>"+20","country"=>"Egypt"],
			["ciso"=>"GQ","code"=>"+240","country"=>"Equatorial Guinea"],
			["ciso"=>"ER","code"=>"+291","country"=>"Eritrea"],
			["ciso"=>"EE","code"=>"+372","country"=>"Estonia"],
			["ciso"=>"ET","code"=>"+251","country"=>"Ethiopia"],
			["ciso"=>"FJ","code"=>"+679","country"=>"Fiji"],
			["ciso"=>"FI","code"=>"+358","country"=>"Finland"],
			["ciso"=>"FR","code"=>"+33","country"=>"France"],
			["ciso"=>"GA","code"=>"+241","country"=>"Gabon"],
			["ciso"=>"GM","code"=>"+220","country"=>"Gambia"],
			["ciso"=>"GE","code"=>"+995","country"=>"Georgia"],
			["ciso"=>"DE","code"=>"+49","country"=>"Germany"],
			["ciso"=>"GH","code"=>"+233","country"=>"Ghana"],
			["ciso"=>"GR","code"=>"+30","country"=>"Greece"],
			["ciso"=>"GD","code"=>"+1473","country"=>"Grenada"],
			["ciso"=>"GT","code"=>"+502","country"=>"Guatemala"],
			["ciso"=>"GN","code"=>"+224","country"=>"Guinea"],
			["ciso"=>"GY","code"=>"+592","country"=>"Guyana"],
			["ciso"=>"HT","code"=>"+509","country"=>"Haiti"],
			["ciso"=>"HN","code"=>"+504","country"=>"Honduras"],
			["ciso"=>"HU","code"=>"+36","country"=>"Hungary"],
			["ciso"=>"IS","code"=>"+354","country"=>"Iceland"],
			["ciso"=>"IN","code"=>"+91","country"=>"India"],
			["ciso"=>"ID","code"=>"+62","country"=>"Indonesia"],
			["ciso"=>"","code"=>"+98","country"=>"Iran"],
			["ciso"=>"IQ","code"=>"+964","country"=>"Iraq"],
			["ciso"=>"IE","code"=>"+353","country"=>"Ireland"],
			["ciso"=>"IL","code"=>"+972","country"=>"Israel"],
			["ciso"=>"IT","code"=>"+39","country"=>"Italy"],
			["ciso"=>"JM","code"=>"+1876","country"=>"Jamaica"],
			["ciso"=>"JP","code"=>"+81","country"=>"Japan"],
			["ciso"=>"JO","code"=>"+962","country"=>"Jordan"],
			["ciso"=>"KZ","code"=>"+76","country"=>"Kazakhstan"],
			["ciso"=>"KE","code"=>"+254","country"=>"Kenya"],
			["ciso"=>"","code"=>"+850","country"=>"North Korea"],
			["ciso"=>"KW","code"=>"+965","country"=>"Kuwait"],
			["ciso"=>"KG","code"=>"+996","country"=>"Kyrgyzstan"],
			["ciso"=>"LA","code"=>"+856","country"=>"Laos"],
			["ciso"=>"LV","code"=>"+371","country"=>"Latvia"],
			["ciso"=>"LB","code"=>"+961","country"=>"Lebanon"],
			["ciso"=>"LY","code"=>"+218","country"=>"Libya"],
			["ciso"=>"LI","code"=>"+423","country"=>"Liechtenstein"],
			["ciso"=>"LT","code"=>"+370","country"=>"Lithuania"],
			["ciso"=>"LU","code"=>"+352","country"=>"Luxembourg"],
			["ciso"=>"MG","code"=>"+261","country"=>"Madagascar"],
			["ciso"=>"MW","code"=>"+265","country"=>"Malawi"],
			["ciso"=>"MY","code"=>"+60","country"=>"Malaysia"],
			["ciso"=>"MV","code"=>"+960","country"=>"Maldives"],
			["ciso"=>"ML","code"=>"+223","country"=>"Mali"],
			["ciso"=>"MT","code"=>"+356","country"=>"Malta"],
			["ciso"=>"MR","code"=>"+222","country"=>"Mauritania"],
			["ciso"=>"MU","code"=>"+230","country"=>"Mauritius"],
			["ciso"=>"MX","code"=>"+52","country"=>"Mexico"],
			["ciso"=>"","code"=>"+373","country"=>"Moldova"],
			["ciso"=>"MC","code"=>"+377","country"=>"Monaco"],
			["ciso"=>"MN","code"=>"+976","country"=>"Mongolia"],
			["ciso"=>"ME","code"=>"+382","country"=>"Montenegro"],
			["ciso"=>"MA","code"=>"+212","country"=>"Morocco"],
			["ciso"=>"MZ","code"=>"+258","country"=>"Mozambique"],
			["ciso"=>"NA","code"=>"+264","country"=>"Namibia"],
			["ciso"=>"NP","code"=>"+977","country"=>"Nepal"],
			["ciso"=>"NL","code"=>"+31","country"=>"Netherlands"],
			["ciso"=>"NZ","code"=>"+64","country"=>"New Zealand"],
			["ciso"=>"NI","code"=>"+505","country"=>"Nicaragua"],
			["ciso"=>"NE","code"=>"+227","country"=>"Niger"],
			["ciso"=>"NG","code"=>"+234","country"=>"Nigeria"],
			["ciso"=>"NO","code"=>"+47","country"=>"Norway"],
			["ciso"=>"OM","code"=>"+968","country"=>"Oman"],
			["ciso"=>"PK","code"=>"+92","country"=>"Pakistan"],
			["ciso"=>"PA","code"=>"+507","country"=>"Panama"],
			["ciso"=>"PY","code"=>"+595","country"=>"Paraguay"],
			["ciso"=>"PE","code"=>"+51","country"=>"Peru"],
			["ciso"=>"PH","code"=>"+63","country"=>"Philippines"],
			["ciso"=>"PL","code"=>"+48","country"=>"Poland"],
			["ciso"=>"PT","code"=>"+351","country"=>"Portugal"],
			["ciso"=>"QA","code"=>"+974","country"=>"Qatar"],
			["ciso"=>"","code"=>"+82","country"=>"South Korea"],
			["ciso"=>"RO","code"=>"+40","country"=>"Romania"],
			["ciso"=>"","code"=>"+7","country"=>"Russia"],
			["ciso"=>"RW","code"=>"+250","country"=>"Rwanda"],
			["ciso"=>"SA","code"=>"+966","country"=>"Saudi Arabia"],
			["ciso"=>"SN","code"=>"+221","country"=>"Senegal"],
			["ciso"=>"RS","code"=>"+381","country"=>"Serbia"],
			["ciso"=>"SC","code"=>"+248","country"=>"Seychelles"],
			["ciso"=>"SL","code"=>"+232","country"=>"Sierra Leone"],
			["ciso"=>"SG","code"=>"+65","country"=>"Singapore"],
			["ciso"=>"SK","code"=>"+421","country"=>"Slovakia"],
			["ciso"=>"SI","code"=>"+386","country"=>"Slovenia"],
			["ciso"=>"SO","code"=>"+252","country"=>"Somalia"],
			["ciso"=>"ZA","code"=>"+27","country"=>"South Africa"],
			["ciso"=>"SS","code"=>"+211","country"=>"South Sudan"],
			["ciso"=>"ES","code"=>"+34","country"=>"Spain"],
			["ciso"=>"LK","code"=>"+94","country"=>"Sri Lanka"],
			["ciso"=>"SD","code"=>"+249","country"=>"Sudan"],
			["ciso"=>"SR","code"=>"+597","country"=>"Suriname"],
			["ciso"=>"SE","code"=>"+46","country"=>"Sweden"],
			["ciso"=>"CH","code"=>"+41","country"=>"Switzerland"],
			["ciso"=>"","code"=>"+963","country"=>"Syria"],
			["ciso"=>"TJ","code"=>"+992","country"=>"Tajikistan"],
			["ciso"=>"","code"=>"+255","country"=>"Tanzania"],
			["ciso"=>"TH","code"=>"+66","country"=>"Thailand"],
			["ciso"=>"TG","code"=>"+228","country"=>"Togo"],
			["ciso"=>"TO","code"=>"+676","country"=>"Tonga"],
			["ciso"=>"TT","code"=>"+1868","country"=>"Trinidad and Tobago"],
			["ciso"=>"TN","code"=>"+216","country"=>"Tunisia"],
			["ciso"=>"TR","code"=>"+90","country"=>"Turkey"],
			["ciso"=>"TM","code"=>"+993","country"=>"Turkmenistan"],
			["ciso"=>"UG","code"=>"+256","country"=>"Uganda"],
			["ciso"=>"UA","code"=>"+380","country"=>"Ukraine"],
			["ciso"=>"AE","code"=>"+971","country"=>"United Arab Emirates"],
			["ciso"=>"","code"=>"+44","country"=>"United Kingdom"],
			["ciso"=>"UY","code"=>"+598","country"=>"Uruguay"],
			["ciso"=>"UZ","code"=>"+998","country"=>"Uzbekistan"],
			["ciso"=>"","code"=>"+58","country"=>"Venezuela"],
			["ciso"=>"","code"=>"+84","country"=>"Vietnam"],
			["ciso"=>"YE","code"=>"+967","country"=>"Yemen"],
			["ciso"=>"ZM","code"=>"+260","country"=>"Zambia"],
			["ciso"=>"ZW","code"=>"+263","country"=>"Zimbabwe"]
    	];
    	/*return $countries = 
	    	[
				'Afghanistan',
				'Albania',
				'Algeria',
				'Andorra',
				'Angola',
				'Argentina',
				'Armenia',
				'Australia',
				'Austria',
				'Azerbaijan',
				'Bahamas',
				'Bahrain',
				'Bangladesh',
				'Barbados',
				'Belarus',
				'Belgium',
				'Bolivia',
				'Bosnia and Herzegovina',
				'Botswana',
				'Brazil',
				'Brunei',
				'Bulgaria',
				'Burma',
				'Burundi',
				'Cambodia',
				'Cameroon',
				'Canada',
				'Central African Republic',
				'Chad',
				'Chile',
				'China',
				'Colombia',
				'Congo',
				'Costa Rica',
				'Cote d’Ivoire (Ivory Coast)',
				'Croatia',
				'Cuba',
				'Cyprus',
				'Czech republic',
				'Denmark',
				'Djibouti',
				'Ecuador',
				'Egypt',
				'Equatorial Guinea',
				'Eritrea',
				'Estonia',
				'Ethiopia',
				'Fiji',
				'Finland',
				'France',
				'Gabon',
				'Gambia',
				'Georgia',
				'Germany',
				'Ghana',
				'Greece',
				'Grenada',
				'Guatemala',
				'Guinea',
				'Guyana',
				'Haiti',
				'Honduras',
				'Hungary',
				'Iceland',
				'India',
				'Indonesia',
				'Iran',
				'Iraq',
				'Ireland',
				'Israel',
				'Italy',
				'Jamaica',
				'Japan',
				'Jordan',
				'Kazakhstan',
				'Kenya',
				'North Korea',
				'Kuwait',
				'Kyrgyzstan',
				'Laos',
				'Latvia',
				'Lebanon',
				'Libya',
				'Liechtenstein',
				'Lithuania',
				'Luxembourg',
				'Madagascar',
				'Malawi',
				'Malaysia',
				'Maldives',
				'Mali',
				'Malta',
				'Mauritania',
				'Mauritius',
				'Mexico',
				'Moldova',
				'Monaco',
				'Mongolia',
				'Montenegro',
				'Morocco',
				'Mozambique',
				'Namibia',
				'Nepal',
				'Netherlands',
				'New Zealand',
				'Nicaragua',
				'Niger',
				'Nigeria',
				'Norway',
				'Oman',
				'Pakistan',
				'Panama',
				'Paraguay',
				'Peru',
				'Philippines',
				'Poland',
				'Portugal',
				'Qatar',
				'South Korea',
				'Romania',
				'Russia',
				'Rwanda',
				'Saudi Arabia',
				'Senegal',
				'Serbia',
				'Seychelles',
				'Sierra Leone',
				'Singapore',
				'Slovakia',
				'Slovenia',
				'Somalia',
				'South Africa',
				'South Sudan',
				'Spain',
				'Sri Lanka',
				'Sudan',
				'Suriname',
				'Sweden',
				'Switzerland',
				'Syria',
				'Tajikistan',
				'Tanzania',
				'Thailand',
				'Togo',
				'Tonga',
				'Trinidad and Tobago',
				'Tunisia',
				'Turkey',
				'Turkmenistan',
				'Uganda',
				'Ukraine',
				'United Arab Emirates',
				'United Kingdom',
				'Uruguay',
				'Uzbekistan',
				'Venezuela',
				'Vietnam',
				'Yemen',
				'Zambia',
				'Zimbabwe',
			];*/
    }
    
  
  

}
